// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwoL8y-Dix8jnq2Im9Z_ihnxWDWoZ-mdU',
    appId: '1:617591025105:web:93c1f8a2c0fd19399084f0',
    messagingSenderId: '617591025105',
    projectId: 'evently-app-912bb',
    authDomain: 'evently-app-912bb.firebaseapp.com',
    storageBucket: 'evently-app-912bb.firebasestorage.app',
    measurementId: 'G-6ZMX0VVYPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Nv_3eFQIILSlFjW7mGv0sskGCEJQUHY',
    appId: '1:617591025105:android:f0ab8566ef7f321b9084f0',
    messagingSenderId: '617591025105',
    projectId: 'evently-app-912bb',
    storageBucket: 'evently-app-912bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZUYoQXY9vyl2hlxGDnJA9up5DWZp6haA',
    appId: '1:617591025105:ios:c4af5bd8feae874c9084f0',
    messagingSenderId: '617591025105',
    projectId: 'evently-app-912bb',
    storageBucket: 'evently-app-912bb.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZUYoQXY9vyl2hlxGDnJA9up5DWZp6haA',
    appId: '1:617591025105:ios:c4af5bd8feae874c9084f0',
    messagingSenderId: '617591025105',
    projectId: 'evently-app-912bb',
    storageBucket: 'evently-app-912bb.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwoL8y-Dix8jnq2Im9Z_ihnxWDWoZ-mdU',
    appId: '1:617591025105:web:b29e31e9a853a07a9084f0',
    messagingSenderId: '617591025105',
    projectId: 'evently-app-912bb',
    authDomain: 'evently-app-912bb.firebaseapp.com',
    storageBucket: 'evently-app-912bb.firebasestorage.app',
    measurementId: 'G-4QCT35PGXB',
  );
}
